<a href="https://colab.research.google.com/github/Ajaysahu01/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
bloodsample = (1,3,5)
print(bloodsample)

(1, 3, 5)


In [ ]:
bloodsample= np.array(bloodsample)

In [ ]:
print(bloodsample)

[1 3 5]


In [ ]:
print(type(bloodsample))

<class 'numpy.ndarray'>


In [ ]:
def function_name ():
  print("ajay")

In [ ]:
def say_hello ():
  print("hello")

In [ ]:
def greet(name):
  print("hello",name)

greet("ajay")
greet("ram")

hello ajay
hello ram


In [ ]:
def add (a,b):
  print(a+b)

add (10,50)
add (50,40)

60
90


In [ ]:
def add (a,b):
  return a+b
result =add(10,20)
print(result)

30


In [ ]:
def change_number(x):
  x=50

number =710
change_number(number)
print(number)

710


In [ ]:
def swap (a,b):
  return b,a
x =20
y =30
x,y=swap(x,y)
print(x,y)

30 20


In [ ]:
def add_number(numbers):
  numbers.append(100)
my_list =[10,20,30]
add_number(my_list)
print(my_list)
#

[10, 20, 30, 100]


In [ ]:
import copy

In [ ]:
numbers =[10,20,30]
new_numbers = copy.copy(numbers)
new_numbers.append(100)
print(numbers)
print(new_numbers)

[10, 20, 30]
[10, 20, 30, 100]


In [ ]:
import numpy as np

In [ ]:
emp_data = {
    "name":[
        "ram","ak","raju"
    ],
    "salary" :(
        5500,
        "9300",
        3900
    )
}

In [ ]:
print(emp_data)

{'name': ['ram', 'ak', 'raju'], 'salary': (5500, '9300', 3900)}


In [ ]:
print(type(emp_data))

<class 'dict'>


In [ ]:
emp_keys = emp_data.keys()
print(emp_keys)


dict_keys(['name', 'salary'])


In [ ]:
emp_salary = emp_data ["salary"]
print(emp_salary)
print(type(emp_salary))

(5500, '9300', 3900)
<class 'tuple'>


In [ ]:
emp_salary = list (emp_salary)
print(emp_salary)
print(type(emp_salary))

[5500, '9300', 3900]
<class 'list'>


In [ ]:
def type_conversion_to_int(emp_salary):
  return [int(x) for x in emp_salary]
converted_salary = type_conversion_to_int(emp_salary)
print(converted_salary)

[5500, 9300, 3900]


In [ ]:
print(type(converted_salary))

<class 'list'>


In [ ]:
print(converted_salary)

[5500, 9300, 3900]


In [ ]:
 print(type(emp_salary))

<class 'list'>


In [ ]:
import numpy as np



In [ ]:
marks =np.array ([
    45,46,47,48,44,11,66
])
print("population:",marks)

population: [45 46 47 48 44 11 66]


In [ ]:
print("population.size",len(marks))

population.size 7


In [ ]:
marks = (11,55)
print(marks)

(11, 55)


In [ ]:
import numpy as np


In [ ]:
weight = np.random.randint(10,20)
print(weight)

15


In [ ]:
marks = np.random.randint(40,90)
print(marks)

76


In [ ]:
import numpy as np

In [ ]:
student ={
    "name":("aj","ak","as"),
    "marks":(55,66,77)
}

In [ ]:
marks =np.array(student["marks"])
print(marks)

[55 66 77]


In [ ]:
np.array((55,66,77)).dtype

dtype('int64')

In [ ]:
np.arange(10,540,55)

array([ 10,  65, 120, 175, 230, 285, 340, 395, 450, 505])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(50,55)

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

full is used to generate our own number


In [ ]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
salary = np.array([5500,4200,3200])
print(salary)

[5500 4200 3200]


In [ ]:
age = np.array([22,25,32])
print(age)

[22 25 32]


In [ ]:
#age
netfix ={
    "watch_hours":(2,3,4)
}
watch_hours = np.array(netfix["watch_hours"])
print(watch_hours)

[2 3 4]


In [ ]:
openai={
    "confidence":(5,6,7)
}
confidence = np.array(openai["confidence"])
print(confidence)


[5 6 7]


In [ ]:
import numpy as np

In [ ]:
year =np.arange(2020,2027)
print(year)

[2020 2021 2022 2023 2024 2025 2026]


In [ ]:
years= np.linspace(2020,2028,10)
print(years )

[2020.         2020.88888889 2021.77777778 2022.66666667 2023.55555556
 2024.44444444 2025.33333333 2026.22222222 2027.11111111 2028.        ]


In [ ]:
empty_batch = np.zeros(10)
print(empty_batch)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
bias = np.ones((13, 14))
print(bias)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
weight = np.full((3,4),0.5)
print(weight)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
rank =np.eye(4)
print("using np.eye",np.identity)
identity = np.identity(4)
print("\n\nusing np.identity.\n",identity)


using np.eye <function identity at 0x7aacf7586980>


using np.identity.
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#constant salary bonus
bonus = np.full(6,5000)
print(bonus)
bonus2=np.full((4,4),3000)
print(bonus2)

[5000 5000 5000 5000 5000 5000]
[[3000 3000 3000 3000]
 [3000 3000 3000 3000]
 [3000 3000 3000 3000]
 [3000 3000 3000 3000]]


In [ ]:
#shapes
#salary data

salary = np.array([[35000,42000], [55000,60000], [33000,35000]])
print(salary)
print(salary.shape
      )

[[35000 42000]
 [55000 60000]
 [33000 35000]]
(3, 2)


In [ ]:
salary = np.array([3500,4500,4000,3000])
print(salary)
print(salary.shape)

[3500 4500 4000 3000]
(4,)


In [ ]:
salary = np.array([[3500],[4000],[4400],[3000],[4720],[4684]])
print(salary)
print(salary.shape)

[[3500]
 [4000]
 [4400]
 [3000]
 [4720]
 [4684]]
(6, 1)


In [ ]:
import numpy as np


In [ ]:
#size


In [ ]:
img = np.linspace(1,50,15)
print(img)

[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]


In [ ]:
img = img.reshape(3,5)
img.shape

(3, 5)

In [ ]:
print(img)

[[ 1.   4.5  8.  11.5 15. ]
 [18.5 22.  25.5 29.  32.5]
 [36.  39.5 43.  46.5 50. ]]


In [ ]:
img.reshape(5,3)
img.shape
print(img)

[[ 1.   4.5  8.  11.5 15. ]
 [18.5 22.  25.5 29.  32.5]
 [36.  39.5 43.  46.5 50. ]]


In [ ]:
img= img.reshape(5,1,3)
print(img)

[[[ 1.   4.5  8. ]]

 [[11.5 15.  18.5]]

 [[22.  25.5 29. ]]

 [[32.5 36.  39.5]]

 [[43.  46.5 50. ]]]


In [ ]:
  img.itemsize

8

In [ ]:
m = np.arange(1,100)
m.dtype

dtype('int64')

In [ ]:
m = np.arange(1,100, dtype=np.float64)
m.dtype

dtype('float64')

In [ ]:
m = np.arange(1,100, dtype=np.float32
            )
m.dtype

dtype('float32')

In [ ]:
m = np.arange(1,100, dtype=np.int16)
m.dtype

dtype('int16')

In [ ]:
xy = np.random.uniform(1,40,10)
print(xy)

[ 9.6526305  19.18349242 26.41461768 28.95171215 30.24668257 27.06401769
 20.00665777  8.04437759 10.95756406 28.20645501]


In [ ]:
xy.dtype

dtype('float64')

In [ ]:
xy.size

10

In [ ]:
marks= np.random.randint(10,50,8)
print(marks)



[36 18 19 15 20 15 25 25]


In [ ]:
marks.fill(5)

In [ ]:
print(marks)

[5 5 5 5 5 5 5 5]


In [ ]:
#TRANSFORM


In [ ]:
marks =np.random.randint(1,100,20)
print(marks)

[ 8 72  6 29 38 13 98 10 58 46 46 59 15 52 95 12 89 68 61 64]


In [ ]:
marks[-5::]

array([12, 89, 68, 61, 64])

In [ ]:
marks[::5]

array([ 8, 13, 46, 12])

In [ ]:
marks[0::2]

array([ 8,  6, 38, 98, 58, 46, 15, 95, 89, 61])

In [ ]:
marks =np.arange(901,2000)
marks[::-1
      ]

array([1999, 1998, 1997, ...,  903,  902,  901])

In [ ]:
year =np.arange(2000,2090)
year.shape

(90,)

In [ ]:
year.size


90

In [ ]:
year.dtype

dtype('int64')

In [ ]:
year.itemsize

8

In [ ]:
year.reshape(15,6)

array([[2000, 2001, 2002, 2003, 2004, 2005],
       [2006, 2007, 2008, 2009, 2010, 2011],
       [2012, 2013, 2014, 2015, 2016, 2017],
       [2018, 2019, 2020, 2021, 2022, 2023],
       [2024, 2025, 2026, 2027, 2028, 2029],
       [2030, 2031, 2032, 2033, 2034, 2035],
       [2036, 2037, 2038, 2039, 2040, 2041],
       [2042, 2043, 2044, 2045, 2046, 2047],
       [2048, 2049, 2050, 2051, 2052, 2053],
       [2054, 2055, 2056, 2057, 2058, 2059],
       [2060, 2061, 2062, 2063, 2064, 2065],
       [2066, 2067, 2068, 2069, 2070, 2071],
       [2072, 2073, 2074, 2075, 2076, 2077],
       [2078, 2079, 2080, 2081, 2082, 2083],
       [2084, 2085, 2086, 2087, 2088, 2089]])

In [ ]:
year[90:100]

array([], dtype=int64)

In [ ]:
year[88:100]

array([2088, 2089])

In [ ]:
#2D's

In [ ]:
year = np.arange(2000,2090)
year.reshape(10,9)

array([[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008],
       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
       [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
       [2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035],
       [2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044],
       [2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053],
       [2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062],
       [2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071],
       [2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080],
       [2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089]])

In [ ]:
year = np.arange(2000,2009)
year.reshape(3,3)

array([[2000, 2001, 2002],
       [2003, 2004, 2005],
       [2006, 2007, 2008]])

In [ ]:
year = np.arange(2001,2010)
year.reshape(3,3)

array([[2001, 2002, 2003],
       [2004, 2005, 2006],
       [2007, 2008, 2009]])

In [ ]:
year[1::1]

array([2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

In [ ]:
year[2::
     ]

array([2003, 2004, 2005, 2006, 2007, 2008, 2009])

In [ ]:
year = year.reshape(3,3)
year[1::,::2]

array([[2004, 2006],
       [2007, 2009]])

In [ ]:
year= year.reshape(3,3)
year[::2,::2]

array([[2001, 2003],
       [2007, 2009]])

In [ ]:
#boolean indexing

In [ ]:
zx= np.random.randint(33,101,20)
zx


array([62, 99, 51, 82, 57, 46, 88, 99, 46, 94, 74, 34, 67, 71, 96, 59, 46,
       82, 66, 71])

In [ ]:
zx[zx>75]

array([99, 82, 88, 99, 94, 96, 82])

In [ ]:
zx[zx<50]

array([46, 46, 34, 46])

In [ ]:
zx[(zx>70)&(zx<90)]

array([82, 88, 74, 71, 82, 71])

In [ ]:
mn= np.random.randint(0,2,20)

In [ ]:
mn[mn==1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])